repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: check-merge-conflict
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8
        args:
          - --line-length=100
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.0.0
    hooks:
      - id: reorder-python-imports
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: trailing-whitespace
        files: "\\.(py|css|less|scss|graphql|gql|js|jsx|json|md|markdown|mdown|mkdn|mdx|ts|tsx|vue|yaml|yml)$"
      - id: check-json
        files: "\\.json$"
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-added-large-files
      - id: check-ast
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: flake8
        args:
          - --max-line-length=101
          - --exclude=*/migrations/*,docs/*
          - --ignore=E126,W503
  - repo: https://github.com/prettier/prettier
    rev: "ca0ff0f2801677f81b149b0381e3de388caaa411"
    hooks:
      - id: prettier
        files: "\\.(css|less|scss|graphql|gql|js|jsx|json|md|markdown|mdown|mkdn|mdx|ts|tsx|vue|yaml|yml)$"
# TODO use instead of flake8
#-   repo: https://github.com/PyCQA/prospector
#    rev: 1.1.7 # The version of Prospector to use, at least 1.1.6
#    hooks:
#    -   id: prospector
